package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"log"
	"os"
	"os/signal"
	"time"

	"encoding/json"
	"io"
	"net/http"
	"strings"

	"github.com/bwmarrin/discordgo"
	"google.golang.org/api/option"

	"cloud.google.com/go/firestore"
	"github.com/GoogleCloudPlatform/functions-framework-go/functions"

	"context"
	"regexp"

	"github.com/google/uuid"
	"google.golang.org/api/iterator"
)

//go:embed banner.png
var bannerPNG []byte

const (
	embedColor  = 0x5865F2
	attendEmoji = "🙋"
)

// buildEventEmbed renders the "new event" embed. when is shown only if non-zero.
func buildEventEmbed(author *discordgo.User, content string, when time.Time, id string) *discordgo.MessageEmbed {
	// Quote every line of the message, in italics.
	lines := strings.Split(strings.TrimSpace(content), "\n")
	for i, l := range lines {
		lines[i] = "> *" + strings.ReplaceAll(l, "*", "\\*") + "*"
	}

	embed := &discordgo.MessageEmbed{
		Author: &discordgo.MessageEmbedAuthor{
			Name:    author.DisplayName() + " is hosting",
			IconURL: author.AvatarURL("64"),
		},
		Description: strings.Join(lines, "\n"),
		Color:       embedColor,
		Image:       &discordgo.MessageEmbedImage{URL: "attachment://banner.png"},
		Footer: &discordgo.MessageEmbedFooter{
			Text: fmt.Sprintf("generated by Study Crowd - %s - React %s to attend", id, attendEmoji),
		},
	}
	if !when.IsZero() {
		embed.Fields = []*discordgo.MessageEmbedField{{Name: "🗓️ When", Value: when.Format("Mon 2 Jan")}}
	}
	return embed
}

var dateRegex = regexp.MustCompile(`(?i)\b(?:` +
	// Relative dates
	`today|tomorrow|yesterday` +
	`|` +
	`(?:this|next|last)\s+` +
	`(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)` +
	`|` +
	// Weekdays
	`(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)` +
	`|` +
	// Explicit dates
	`\d{4}[-/]\d{1,2}[-/]\d{1,2}` +
	`|` +
	`\d{1,2}[-/]\d{1,2}[-/]\d{4}` +
	`|` +
	`\d{1,2}(?:st|nd|rd|th)?\s+` +
	`(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*` +
	`(?:\s+\d{4})?` +
	`|` +
	`(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+` +
	`\d{1,2}(?:st|nd|rd|th)?(?:,?\s+\d{4})?` +
	`)\b`)

func extractDate(message string, now time.Time) (string, time.Time, bool) {
	match := dateRegex.FindString(message)
	if match == "" {
		return "", time.Time{}, false
	}

	match = strings.ToLower(strings.TrimSpace(match))

	fmt.Println(match)

	switch match {
	case "today":
		return match, now, true

	case "tomorrow":
		return match, now.AddDate(0, 0, 1), true

	case "yesterday":
		return match, now.AddDate(0, 0, -1), true
	}

	parts := strings.Fields(match)

	if len(parts) == 2 {
		var offset int
		switch parts[0] {
		case "next":
			offset = 1
		case "last":
			offset = -1
		case "this":
			offset = 0
		}

		if offset != 0 || parts[0] == "this" {
			weekday := parseWeekday(parts[1])
			if weekday >= 0 {
				return match, resolveWeekday(now, weekday, offset), true
			}
		}
	}

	// Plain weekday: choose the next occurrence.
	if weekday := parseWeekday(match); weekday >= 0 {
		return match, resolveWeekday(now, weekday, 0), true
	}

	// Add explicit date parsing here if required.
	return match, time.Time{}, true
}

func parseWeekday(s string) time.Weekday {
	switch strings.ToLower(s) {
	case "sunday":
		return time.Sunday
	case "monday":
		return time.Monday
	case "tuesday":
		return time.Tuesday
	case "wednesday":
		return time.Wednesday
	case "thursday":
		return time.Thursday
	case "friday":
		return time.Friday
	case "saturday":
		return time.Saturday
	default:
		return -1
	}
}

func resolveWeekday(now time.Time, target time.Weekday, modifier int) time.Time {
	current := now.Weekday()

	days := (int(target) - int(current) + 7) % 7

	switch modifier {
	case 1: // next
		if days == 0 {
			days = 7
		} else {
			days += 7
		}

	case -1: // last
		if days == 0 {
			days = 7
		}
		days -= 7

	case 0: // this / plain weekday
		// Keep the current week.
	}

	return now.AddDate(0, 0, days)
}

type JevMessage struct {
	Category string `json:"category"`
}

func jevCall(bearerToken string, message string) (JevMessage, error) {
	var jevMsg JevMessage

	msg := map[string]any{
		"message": message,
	}

	b, err := json.Marshal(msg)
	if err != nil {
		return jevMsg, err
	}

	// fmt.Println(string(b))
	req, err := http.NewRequest("POST", "https://classifydiscordmessage-jj62desesa-uc.a.run.app", strings.NewReader(string(b)))
	if err != nil {
		return jevMsg, err
	}

	req.Header.Set("Authorization", "Bearer "+bearerToken)
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return jevMsg, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return jevMsg, fmt.Errorf("classifier returned %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return jevMsg, err
	}
	// fmt.Println(string(body))
	if err := json.Unmarshal(body, &jevMsg); err != nil {
		return jevMsg, err
	}

	return jevMsg, nil
}

func handleMessageSent(jevBearerToken string, db *firestore.Client, s *discordgo.Session, r *discordgo.MessageCreate) {
	// curl -X POST "https://classifydiscordmessage-jj62desesa-uc.a.run.app"   -H "Content-Type: application/json"   -d '{"message":"im down to go to the burger event!"}' -H "Authorization: Bearer bazinga"

	if r.Author.Bot {
		return
	}

	jevRes, err := jevCall(jevBearerToken, r.Content)

	if err != nil {
		log.Printf("failed to classify message: %v", err)
		return
	}

	fmt.Println(jevRes.Category)
	if jevRes.Category == "new_event" {
		eventID := uuid.NewString()
		post := map[string]any{
			"uuid":      eventID,
			"createdAt": time.Now().Unix(),
			"author":    r.Author.ID,
			"title":     r.Content,
			"attending": []string{r.Author.ID},
		}

		_, t, _ := extractDate(r.Content, time.Now())
		if !t.IsZero() {
			post["timestamp"] = t.Unix()
		}

		msg, err := s.ChannelMessageSendComplex(r.ChannelID, &discordgo.MessageSend{
			Embeds: []*discordgo.MessageEmbed{buildEventEmbed(r.Author, r.Content, t, eventID[:8])},
			Files:  []*discordgo.File{{Name: "banner.png", ContentType: "image/png", Reader: bytes.NewReader(bannerPNG)}},
		})
		if err != nil {
			log.Printf("failed to send event embed: %v", err)
			return
		}

		if err := s.MessageReactionAdd(r.ChannelID, msg.ID, attendEmoji); err != nil {
			log.Printf("failed to add %s reaction: %v", attendEmoji, err)
		}

		post["embed_message_id"] = msg.ID

		_, _, err = db.Collection("posts").Add(context.Background(), post)
		if err != nil {
			return
		}
	}
}

// isSelf reports whether userID is the bot (its seed reaction is not an attendee).
func isSelf(s *discordgo.Session, userID string) bool {
	return s.State != nil && s.State.User != nil && s.State.User.ID == userID
}

func handleReactionAdd(db *firestore.Client, s *discordgo.Session, r *discordgo.MessageReactionAdd) {
	if isSelf(s, r.UserID) {
		return
	}
	ctx := context.Background()

	// Find the event corresponding to the Discord message.
	iter := db.Collection("posts").
		Where("embed_message_id", "==", r.MessageID).
		Limit(1).
		Documents(ctx)

	doc, err := iter.Next()
	if err == iterator.Done {
		return // Not an event message.
	}
	if err != nil {
		log.Printf("failed to find event: %v", err)
		return
	}

	// Add the user to the attendance list.
	_, err = doc.Ref.Update(ctx, []firestore.Update{
		{
			Path:  "attending",
			Value: firestore.ArrayUnion(r.UserID),
		},
	})
	if err != nil {
		log.Printf("failed to add attendee: %v", err)
		return
	}

	log.Printf("user %s joined event %s", r.UserID, doc.Ref.ID)
}

func handleReactionRemove(db *firestore.Client, s *discordgo.Session, r *discordgo.MessageReactionRemove) {
	if isSelf(s, r.UserID) {
		return
	}
	ctx := context.Background()

	// Find the event corresponding to the Discord message.
	iter := db.Collection("posts").
		Where("embed_message_id", "==", r.MessageID).
		Limit(1).
		Documents(ctx)

	doc, err := iter.Next()
	if err == iterator.Done {
		return // Not an event message.
	}
	if err != nil {
		log.Printf("failed to find event: %v", err)
		return
	}

	// Remove the user from the attendance list.
	_, err = doc.Ref.Update(ctx, []firestore.Update{
		{
			Path:  "attending",
			Value: firestore.ArrayRemove(r.UserID),
		},
	})
	if err != nil {
		log.Printf("failed to remove attendee: %v", err)
		return
	}

	log.Printf("user %s left event %s", r.UserID, doc.Ref.ID)
}

const firestoreDatabase = "studycrowd-db1"

// newFirestoreClient uses FIRESTORE_PROJECT_ID and FIRESTORE_API_KEY when both are set
// (local or sandbox runs). Otherwise it falls back to the project and credentials
// detected from the environment, as on Cloud Run.
func newFirestoreClient(ctx context.Context) (*firestore.Client, error) {
	project, key := os.Getenv("FIRESTORE_PROJECT_ID"), os.Getenv("FIRESTORE_API_KEY")
	if project != "" && key != "" {
		log.Printf("firestore: using FIRESTORE_PROJECT_ID %q with an API key", project)
		return firestore.NewClientWithDatabase(ctx, project, firestoreDatabase, option.WithAPIKey(key))
	}
	log.Print("firestore: using detected project and credentials")
	return firestore.NewClientWithDatabase(ctx, firestore.DetectProjectID, firestoreDatabase)
}

// discordBotToken prefers DISCORD_BOT_TOKEN and falls back to the older DISCORD_TOKEN.
func discordBotToken() string {
	if t := os.Getenv("DISCORD_BOT_TOKEN"); t != "" {
		return t
	}
	return os.Getenv("DISCORD_TOKEN")
}

func main() {
	db, err := newFirestoreClient(context.Background())
	if err != nil {
		panic(err)
	}

	session, err := discordgo.New("Bot " + discordBotToken())

	if err != nil {
		fmt.Println(err.Error())
		return
	}

	jevToken := os.Getenv("CLIENT_AUTH_TOKEN")

	session.AddHandler(func(s *discordgo.Session, r *discordgo.Ready) {
		log.Printf("Logged in as %s", r.User.String())
	})

	session.AddHandler(func(s *discordgo.Session, r *discordgo.MessageCreate) {
		handleMessageSent(jevToken, db, s, r)
	})

	session.AddHandler(func(s *discordgo.Session, r *discordgo.MessageReactionAdd) {
		handleReactionAdd(db, s, r)
	})

	session.AddHandler(func(s *discordgo.Session, r *discordgo.MessageReactionRemove) {
		handleReactionRemove(db, s, r)
	})

	err = session.Open()
	if err != nil {
		log.Fatalf("could not open session: %s", err)
	}

	sigch := make(chan os.Signal, 1)
	signal.Notify(sigch, os.Interrupt)
	<-sigch

	err = session.Close()
	if err != nil {
		log.Printf("could not close session gracefully: %s", err)
	}

	functions.HTTP("health", health)

}

func health(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "up")
}
