package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"log"
	"os"
	"os/signal"
	"time"

	"encoding/json"
	"io"
	"net/http"
	"strings"

	"github.com/bwmarrin/discordgo"
	"google.golang.org/api/option"

	"cloud.google.com/go/firestore"
	"github.com/GoogleCloudPlatform/functions-framework-go/functions"

	"context"
	"regexp"

	"github.com/google/uuid"
	"google.golang.org/api/iterator"
)

//go:embed banner.png
var bannerPNG []byte

const (
	embedColor  = 0x5865F2
	attendEmoji = "🙋"
	bannerFile  = "banner.png"
	shortIDLen  = 8 // length of the event ID shown in the embed footer
)

// buildEventEmbed renders the "new event" embed. when is shown only if non-zero.
func buildEventEmbed(author *discordgo.User, content string, when time.Time, shortID string) *discordgo.MessageEmbed {
	// Quote every line of the message, in italics.
	lines := strings.Split(strings.TrimSpace(content), "\n")
	for i, l := range lines {
		lines[i] = "> *" + strings.ReplaceAll(l, "*", "\\*") + "*"
	}

	embed := &discordgo.MessageEmbed{
		Author: &discordgo.MessageEmbedAuthor{
			Name:    author.DisplayName() + " is hosting",
			IconURL: author.AvatarURL("64"),
		},
		Description: strings.Join(lines, "\n"),
		Color:       embedColor,
		Image:       &discordgo.MessageEmbedImage{URL: "attachment://" + bannerFile},
		Footer:      eventFooter(shortID, 1), // the host is the first attendee
	}
	if !when.IsZero() {
		embed.Fields = []*discordgo.MessageEmbedField{{Name: "🗓️ When", Value: when.Format("Mon 2 Jan")}}
	}
	return embed
}

// eventFooter carries the going count, so it is rebuilt whenever attendance changes.
func eventFooter(shortID string, going int) *discordgo.MessageEmbedFooter {
	return &discordgo.MessageEmbedFooter{
		Text: fmt.Sprintf("generated by Study Crowd - %s - %d going - React %s to attend", shortID, going, attendEmoji),
	}
}

var dateRegex = regexp.MustCompile(`(?i)\b(?:` +
	// Relative dates
	`today|tomorrow|yesterday` +
	`|` +
	`(?:this|next|last)\s+` +
	`(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)` +
	`|` +
	// Weekdays
	`(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)` +
	`|` +
	// Explicit dates
	`\d{4}[-/]\d{1,2}[-/]\d{1,2}` +
	`|` +
	`\d{1,2}[-/]\d{1,2}[-/]\d{4}` +
	`|` +
	`\d{1,2}(?:st|nd|rd|th)?\s+` +
	`(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*` +
	`(?:\s+\d{4})?` +
	`|` +
	`(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+` +
	`\d{1,2}(?:st|nd|rd|th)?(?:,?\s+\d{4})?` +
	`)\b`)

func extractDate(message string, now time.Time) (string, time.Time, bool) {
	match := dateRegex.FindString(message)
	if match == "" {
		return "", time.Time{}, false
	}

	match = strings.ToLower(strings.TrimSpace(match))

	fmt.Println(match)

	switch match {
	case "today":
		return match, now, true

	case "tomorrow":
		return match, now.AddDate(0, 0, 1), true

	case "yesterday":
		return match, now.AddDate(0, 0, -1), true
	}

	parts := strings.Fields(match)

	if len(parts) == 2 {
		var offset int
		switch parts[0] {
		case "next":
			offset = 1
		case "last":
			offset = -1
		case "this":
			offset = 0
		}

		if offset != 0 || parts[0] == "this" {
			weekday := parseWeekday(parts[1])
			if weekday >= 0 {
				return match, resolveWeekday(now, weekday, offset), true
			}
		}
	}

	// Plain weekday: choose the next occurrence.
	if weekday := parseWeekday(match); weekday >= 0 {
		return match, resolveWeekday(now, weekday, 0), true
	}

	// Add explicit date parsing here if required.
	return match, time.Time{}, true
}

func parseWeekday(s string) time.Weekday {
	switch strings.ToLower(s) {
	case "sunday":
		return time.Sunday
	case "monday":
		return time.Monday
	case "tuesday":
		return time.Tuesday
	case "wednesday":
		return time.Wednesday
	case "thursday":
		return time.Thursday
	case "friday":
		return time.Friday
	case "saturday":
		return time.Saturday
	default:
		return -1
	}
}

func resolveWeekday(now time.Time, target time.Weekday, modifier int) time.Time {
	current := now.Weekday()

	days := (int(target) - int(current) + 7) % 7

	switch modifier {
	case 1: // next
		if days == 0 {
			days = 7
		} else {
			days += 7
		}

	case -1: // last
		if days == 0 {
			days = 7
		}
		days -= 7

	case 0: // this / plain weekday
		// Keep the current week.
	}

	return now.AddDate(0, 0, days)
}

type JevMessage struct {
	Category string `json:"category"`
}

func jevCall(bearerToken string, message string) (JevMessage, error) {
	var jevMsg JevMessage

	msg := map[string]any{
		"message": message,
	}

	b, err := json.Marshal(msg)
	if err != nil {
		return jevMsg, err
	}

	// fmt.Println(string(b))
	req, err := http.NewRequest("POST", "https://classifydiscordmessage-jj62desesa-uc.a.run.app", strings.NewReader(string(b)))
	if err != nil {
		return jevMsg, err
	}

	req.Header.Set("Authorization", "Bearer "+bearerToken)
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return jevMsg, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return jevMsg, fmt.Errorf("classifier returned %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return jevMsg, err
	}
	// fmt.Println(string(body))
	if err := json.Unmarshal(body, &jevMsg); err != nil {
		return jevMsg, err
	}

	return jevMsg, nil
}

func handleMessageSent(jevBearerToken string, db *firestore.Client, s *discordgo.Session, r *discordgo.MessageCreate) {
	// curl -X POST "https://classifydiscordmessage-jj62desesa-uc.a.run.app"   -H "Content-Type: application/json"   -d '{"message":"im down to go to the burger event!"}' -H "Authorization: Bearer bazinga"

	if r.Author.Bot {
		return
	}

	jevRes, err := jevCall(jevBearerToken, r.Content)

	if err != nil {
		log.Printf("failed to classify message: %v", err)
		return
	}

	fmt.Println(jevRes.Category)
	if jevRes.Category == "new_event" {
		eventID := uuid.NewString()
		post := map[string]any{
			"uuid":      eventID,
			"createdAt": time.Now().Unix(),
			"author":    r.Author.ID,
			"title":     r.Content,
			"attending": []string{r.Author.ID},
		}

		_, t, _ := extractDate(r.Content, time.Now())
		if !t.IsZero() {
			post["timestamp"] = t.Unix()
		}

		msg, err := s.ChannelMessageSendComplex(r.ChannelID, &discordgo.MessageSend{
			Embeds: []*discordgo.MessageEmbed{buildEventEmbed(r.Author, r.Content, t, eventID[:shortIDLen])},
			Files:  []*discordgo.File{{Name: bannerFile, ContentType: "image/png", Reader: bytes.NewReader(bannerPNG)}},
		})
		if err != nil {
			log.Printf("failed to send event embed: %v", err)
			return
		}

		if err := s.MessageReactionAdd(r.ChannelID, msg.ID, attendEmoji); err != nil {
			log.Printf("failed to add %s reaction: %v", attendEmoji, err)
		}

		post["embed_message_id"] = msg.ID
		post["channel_id"] = msg.ChannelID

		if _, _, err := db.Collection("posts").Add(context.Background(), post); err != nil {
			log.Printf("failed to save event %s: %v", eventID, err)
		}
	}
}

// isSelf reports whether userID is the bot (its seed reaction is not an attendee).
func isSelf(s *discordgo.Session, userID string) bool {
	return s.State != nil && s.State.User != nil && s.State.User.ID == userID
}

func handleReactionAdd(db *firestore.Client, s *discordgo.Session, r *discordgo.MessageReactionAdd) {
	updateAttendance(db, s, r.MessageReaction, true)
}

func handleReactionRemove(db *firestore.Client, s *discordgo.Session, r *discordgo.MessageReactionRemove) {
	updateAttendance(db, s, r.MessageReaction, false)
}

// updateAttendance adds or removes the reacting user as an attendee of the event whose
// embed received the reaction, and saves or unsaves the post for them, the same way
// RSVPing in the app does. Only the attend emoji counts, and the bot's own seed
// reaction is ignored.
func updateAttendance(db *firestore.Client, s *discordgo.Session, r *discordgo.MessageReaction, going bool) {
	if r.Emoji.Name != attendEmoji || isSelf(s, r.UserID) {
		return
	}
	ctx := context.Background()

	// Find the event corresponding to the Discord message.
	doc, err := db.Collection("posts").
		Where("embed_message_id", "==", r.MessageID).
		Limit(1).
		Documents(ctx).
		Next()
	if err == iterator.Done {
		return // Not an event message.
	}
	if err != nil {
		log.Printf("failed to find event: %v", err)
		return
	}

	bookmark := db.Collection("users").Doc(r.UserID).Collection("bookmarks").Doc(doc.Ref.ID)
	batch := db.Batch()
	if going {
		post := doc.Data()
		batch.Update(doc.Ref, []firestore.Update{{Path: "attending", Value: firestore.ArrayUnion(r.UserID)}})
		batch.Set(bookmark, map[string]any{
			"bookmarkedAt":  firestore.ServerTimestamp,
			"postId":        doc.Ref.ID,
			"title":         post["title"],
			"author":        post["author"],
			"postCreatedAt": post["createdAt"],
			"postUuid":      post["uuid"],
		})
	} else {
		batch.Update(doc.Ref, []firestore.Update{{Path: "attending", Value: firestore.ArrayRemove(r.UserID)}})
		batch.Delete(bookmark)
	}
	if _, err := batch.Commit(ctx); err != nil {
		log.Printf("failed to update attendance: %v", err)
		return
	}

	log.Printf("user %s going=%t to event %s", r.UserID, going, doc.Ref.ID)
}

// watchGoingCounts keeps each event embed's going count in sync with Firestore, so
// RSVPs made in the app (as well as reactions) show up on Discord.
func watchGoingCounts(ctx context.Context, db *firestore.Client, s *discordgo.Session) {
	snapshots := db.Collection("posts").Snapshots(ctx)
	defer snapshots.Stop()
	for {
		snap, err := snapshots.Next()
		if err != nil {
			log.Printf("stopped watching posts: %v", err)
			return
		}
		for _, change := range snap.Changes {
			if change.Kind == firestore.DocumentModified {
				refreshGoingCount(s, change.Doc)
			}
		}
	}
}

// refreshGoingCount rewrites the embed footer of a post if its going count changed.
func refreshGoingCount(s *discordgo.Session, doc *firestore.DocumentSnapshot) {
	var post struct {
		UUID      string   `firestore:"uuid"`
		ChannelID string   `firestore:"channel_id"`
		MessageID string   `firestore:"embed_message_id"`
		Attending []string `firestore:"attending"`
	}
	if err := doc.DataTo(&post); err != nil || post.ChannelID == "" || len(post.UUID) < shortIDLen {
		return // Posts from before channel_id was stored cannot be located.
	}

	msg, err := s.ChannelMessage(post.ChannelID, post.MessageID)
	if err != nil || len(msg.Embeds) == 0 {
		log.Printf("failed to fetch embed for event %s: %v", doc.Ref.ID, err)
		return
	}
	embed := msg.Embeds[0]
	footer := eventFooter(post.UUID[:shortIDLen], len(post.Attending))
	if embed.Footer != nil && embed.Footer.Text == footer.Text {
		return
	}
	embed.Footer = footer
	// A fetched embed points at the banner's CDN URL; without the attachment:// reference
	// Discord would also show the banner as a separate attachment.
	embed.Image = &discordgo.MessageEmbedImage{URL: "attachment://" + bannerFile}
	if _, err := s.ChannelMessageEditEmbed(post.ChannelID, post.MessageID, embed); err != nil {
		log.Printf("failed to update going count for event %s: %v", doc.Ref.ID, err)
		return
	}
	log.Printf("event %s: %d going", doc.Ref.ID, len(post.Attending))
}

const firestoreDatabase = "studycrowd-db1"

// newFirestoreClient uses FIRESTORE_PROJECT_ID and FIRESTORE_API_KEY when both are set
// (local or sandbox runs). Otherwise it falls back to the project and credentials
// detected from the environment, as on Cloud Run.
func newFirestoreClient(ctx context.Context) (*firestore.Client, error) {
	project, key := os.Getenv("FIRESTORE_PROJECT_ID"), os.Getenv("FIRESTORE_API_KEY")
	if project != "" && key != "" {
		log.Printf("firestore: using FIRESTORE_PROJECT_ID %q with an API key", project)
		// passthrough makes gRPC dial the hostname rather than a resolved IP, so an HTTPS proxy
		// that allows hosts by name (as in sandboxed runs) can tunnel the connection.
		return firestore.NewClientWithDatabase(ctx, project, firestoreDatabase,
			option.WithAPIKey(key), option.WithEndpoint("passthrough:///firestore.googleapis.com:443"))
	}
	log.Print("firestore: using detected project and credentials")
	return firestore.NewClientWithDatabase(ctx, firestore.DetectProjectID, firestoreDatabase)
}

// discordBotToken prefers DISCORD_BOT_TOKEN and falls back to the older DISCORD_TOKEN.
func discordBotToken() string {
	if t := os.Getenv("DISCORD_BOT_TOKEN"); t != "" {
		return t
	}
	return os.Getenv("DISCORD_TOKEN")
}

func main() {
	db, err := newFirestoreClient(context.Background())
	if err != nil {
		panic(err)
	}

	session, err := discordgo.New("Bot " + discordBotToken())

	if err != nil {
		fmt.Println(err.Error())
		return
	}

	jevToken := os.Getenv("CLIENT_AUTH_TOKEN")

	session.AddHandler(func(s *discordgo.Session, r *discordgo.Ready) {
		log.Printf("Logged in as %s", r.User.String())
	})

	session.AddHandler(func(s *discordgo.Session, r *discordgo.MessageCreate) {
		handleMessageSent(jevToken, db, s, r)
	})

	session.AddHandler(func(s *discordgo.Session, r *discordgo.MessageReactionAdd) {
		handleReactionAdd(db, s, r)
	})

	session.AddHandler(func(s *discordgo.Session, r *discordgo.MessageReactionRemove) {
		handleReactionRemove(db, s, r)
	})

	err = session.Open()
	if err != nil {
		log.Fatalf("could not open session: %s", err)
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	defer stop()
	go watchGoingCounts(ctx, db, session)
	<-ctx.Done()

	err = session.Close()
	if err != nil {
		log.Printf("could not close session gracefully: %s", err)
	}

	functions.HTTP("health", health)

}

func health(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "up")
}
